version: "3.3"

services:
  portal-db:
    container_name: portal-db
    image: postgres:14
    restart: always
    networks:
      portal-net:
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5433:5432"

  portal:
    container_name: portal
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      portal-net:
    environment:
      - JDBC_URL=jdbc:postgresql://portal-db:5432/${POSTGRES_DB}
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TWITTER_API_KEY
      - TWITTER_SECRET_KEY
      - TWITTER_ACCESS_TOKEN
      - TWITTER_SECRET_TOKEN
    ports:
      - "8080:8080"
    depends_on:
      - portal-db

volumes:
  postgres-data:
  pgadmin-data:

networks:
  portal-net:
