spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/portal}
    driver-class-name: "org.postgresql.Driver"
    username: ${POSTGRES_USER:portal}
    password: ${POSTGRES_PASSWORD:portal}
  flyway:
    outOfOrder: true
    locations: classpath:db/migration

server:
  servlet:
    contextPath: /api
