spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/portal}
    driver-class-name: "org.postgresql.Driver"
    username: ${POSTGRES_USER:portal}
    password: ${POSTGRES_PASSWORD:portal}
  flyway:
    outOfOrder: true
    locations: classpath:db/migration

server:
  servlet:
    contextPath: /api

twitter:
  api_key: ${TWITTER_API_KEY}
  secret_key: ${TWITTER_SECRET_KEY}
  access_token: ${TWITTER_ACCESS_TOKEN}
  secret_token: ${TWITTER_SECRET_TOKEN}
